### ISSUE TITLE
`generatejsonschematypes` fails on linux \ WSL

### ISSUE THREAD

**Issue by mrt181** [corvus-dotnet/Corvus.JsonSchema#292] opened 2024-02-19 15:45 UTC
I am using a schema that references other schema files in the same directory.

I can generate the code files running this command:
```bash
generatejsonschematypes --rootNamespace app.Infrastructure my-schema.json --outputRootTypeName MyType --outputPath ..\Data
Generating: Node
Generating: IdEntity
Generating: UnitEntity
Generating: MyType
...
```

When I copy the project to WSL and rerun the same command I get this error:
```bash
generatejsonschematypes --rootNamespace stow.Infrastructure my-schema.json --outputRootTypeName MyType --outputPath ..\Data
Unable to locate the root document at 'home/myuser/repos/myproject/src/app.Infrastructure/Schema/node-schema.json'
```

**Comment by mwadams** [comment] 2024-02-19 15:51
Thanks for this. We'll investigate.

**Comment by mwadams** [comment] 2024-02-27 09:02
How are you formatting the `$ref` in your schema? We support UNIX-style paths on both windows and UNIX but Windows-style paths only work on Windows.

e.g. 

Create a file baseschema.json

```json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "allOf": [
        {
            "$ref": "./schema.json#"
        },
        {
            "type": "object",
            "properties": {
                "foo": {
                    "type": "number",
                    "minimum": 5
                }
            }
        }
    ]
}
```

Create a file schema.json

```json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "properties": {
        "foo": {
            "type": "number",
            "minimum": 0
        }
    }
}
```
Running the type generator

```
generatejsonschematypes.exe --rootNamespace Example --outputPath Generated ./baseschema.json
```

Emits the results:

```
Generating: BaseschemaJson
Generating: FooEntity
Generating: AllOf1Entity
Generating: FooEntity
Generating: SchemaJson
```

**Comment by mwadams** [comment] 2024-03-05 10:34
@mrt181 - Have you had a chance to verify this issue?

**Comment by JamesDawson** [comment] 2024-03-06 18:21
This looks like an issue with using Windows style paths on the WSL command-line.

The original repro has the following `--outputPath ..\Data`

I can repro the original error in WSL using the sample from @mwadams with the following:
```
generatejsonschematypes.exe --rootNamespace Example --outputPath Generated .\baseschema.json
```

**Comment by mwadams** [comment] 2024-03-06 18:32
As I say, we don't support Windows-style paths on UNIX. But we support both path styles in Windows.

**Comment by mwadams** [comment] 2024-03-11 11:05
I am closing this as "by design". Feel free to re-open if we have misunderstood your issue.

**Closed as not planned by mwadams** 2024-03-11 11:05 UTC
Labels: review
